### ISSUE TITLE
Build Errors in Example due to OMR references

### ISSUE THREAD

**Issue by RoomTemprature** [aspose-ocr/Aspose.OCR-for-.NET#23]
I believe OMR has been removed from OCR in one of the recent updates to ASPOSE OCR, however the examples still contain numerous references to OMR and therefore fail to build successfully.

**Comment by m-ikramulhaq** [comment]
Yes, you are correct. OMR namespace has been removed. You may now try to pull the latest version of Aspose.OCR for .NET. The issues have been resolved. We are sorry for the inconvenience.
