### ISSUE TITLE
OCR not reading tiff file effectively

### ISSUE THREAD

**Issue by RoomTemprature** [aspose-ocr/Aspose.OCR-for-.NET#25]
The included tiff file (SampleTiff.tiff) does not seem to be well processed by the OCR. I tried targetting it with PerformOCROnImage.Run() and tried just uncommenting OCROnMultipageTIFF.Run(), both with lackluster results. Both output only one line (similar in both cases), and its unclear where the line is coming from in the tiff file.

**Comment by kashifiqb** [comment]
@RoomTemprature ,

We are analyzing your mentioned issues and will soon update you with our findings here.

**Comment by m-ikramulhaq** [comment]
@RoomTemprature,

You are correct. Output after performing Aspose.OCR operation on this image is not correct. This image has colored background. At the moment, Aspose.OCR has issues with colorful backgrounds. This issue has already been logged into our system. 

We are sorry for the inconvenience.

**Comment by RoomTemprature** [comment]
Thanks for the update. The OCR also seems to struggle with crowded images, such as sample1.jpg, but I'm guessing that's not a simple fix either. That image doesn't have a colored back ground.

**Comment by kashifiqb** [comment]
We will look into it along with the issue already reported earlier.

**Comment by m-ikramulhaq** [comment]
This image can be used with User Defined Recognition Block option [**AddRecognitionBlock**]. Further, the image contains data in tabular format. Please note that current implementation does not support extracting data from table format. This issue has also been logged into our system.
