### ISSUE TITLE
AsposeOcr().RecognizeImage produces additional images 

### ISSUE THREAD

**Issue by dzajda** [aspose-ocr/Aspose.OCR-for-.NET#29]
Hi,
I cannot find that info in the documentation for .NET.

Looks like that `new AsposeOcr().RecognizeImage(dataDir + "Sampleocr.bmp");` produces additional images "Row_exampleX.png" and stores it in the project folder.

Is it possible to manage it? Now, I need to remember to delete it after performing the image recognition.

**Comment by asadalikhan90** [comment]
@dzajda 

Can you please try again using the latest version of the API i.e. [Aspose.OCR for .NET 22.5](https://downloads.aspose.com/ocr/net/new-releases/-aspose.ocr-for-net-22.5/) and let us know in case you still notice same behavior. Please try to create a post in [our official support forum](https://forum.aspose.com/c/ocr) which is the right place to report such issues and you can also track their progress there.

**Comment by somk** [comment]
已经收到。
