### ISSUE TITLE
compiliing samples fails ASP Core 6 , BS 5 update

### ISSUE THREAD

**Issue by fasteddys** [aspose-ocr/Aspose.OCR-for-.NET#33]
Hello I am trying to find a sample that can extract  text from images and PDF and give me an success rating 90% confidence etc.

Its not compiling in VS 2022 with asp core 6
the nugets are also outdated
how to get the confidence rating on the OCR after processing.
how to display text side by side with original document / scrolling web view, so user can compare both

**Comment by somk** [comment]
已经收到。

**Comment by fasteddys** [comment]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Cloud' does not exist in the namespace 'Aspose.OCR' (are you missing an assembly reference?)	Aspose.OCR.Live.Demos.UI	C:\Aspose.OCR.Live.Demos.UI\Models\AsposeOCR.cs	5	Active
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'TransportSync' could not be found (are you missing a using directive or an assembly reference?)	Aspose.OCR.Live.Demos.UI	C:\Aspose.OCR.Live.Demos.UI\Models\AsposeOCR.cs	27	Active

```

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'OcrRecognizeRequest' could not be found (are you missing a using directive or an assembly reference?)	Aspose.OCR.Live.Demos.UI	C:\Aspose.OCR.Live.Demos.UI\Models\AsposeOCR.cs	48	Active


```

Many more errors

**Comment by asadalikhan90** [comment]
@fasteddys 

We are checking the scenario and will get back to you shortly.

**Comment by asadalikhan90** [comment]
@fasteddys 

We regret to inform you that Aspose.OCR for .NET cannot be used under .NET Core 6.0 because it uses System.Drawing dependency which is not supported in .NET Core 6.0. We are working on replacing the dependency with one of our own components. We request you please create a post in the official [Aspose.OCR Support forum](https://forum.aspose.com/c/ocr) where we will attach a ticket ID logged for this task so that you will be able to track the progress there properly. We apologize for the inconvenience.

**Comment by fasteddys** [comment]
I tried in .net 3.1 and 5 still doesnt work. Can you tell me which nuget package works works with .net core 6

I dont a have a livenss to post ticket, just a developer

**Comment by asadalikhan90** [comment]
@fasteddys 

Please note that .NET Core 6.0 support is never introduced for any versions of the API. **OCRNET-467** is the ticket ID that has been logged in our issue tracking system to implement it. We will surely announce as soon as the support of .NET Core 6.0 is added.

Please try to create a new simple Console Application and install [21.12](https://www.nuget.org/packages/Aspose.OCR/21.12) version of Aspose.OCR for .NET from NuGet Gallery. You can then notice and share with us what issue you are facing while building the solution. You can also check the API documentation for code examples and samples. 

Furthermore, if you are trying to use the [Demos](https://github.com/aspose-ocr/Aspose.OCR-for-.NET/tree/master/Demos/src/Aspose.OCR.Live.Demos.UI) given over GitHub and facing some issues while compiling or running them, [Aspose Apps Forum](https://forum.aspose.app/) is the right place to post them and you will be assisted accordingly.

**Comment by fasteddys** [comment]
we got another package for now. thanks.
